DROP TABLE IF EXISTS Houses;
CREATE TABLE Houses (
    houseID INT AUTO_INCREMENT PRIMARY KEY,
    userID INT NOT NULL,
    address VARCHAR(255) NOT NULL,
    FOREIGN KEY (userID) REFERENCES Users(userID)
);
